# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=100)),
            ],
        ),
    ]
