# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfems', '0002_loginx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=100),
        ),
    ]
